// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Image struct {
	ID     int64
	Link   sql.NullString
	Title  sql.NullString
	Date   sql.NullString
	Source sql.NullString
	Author sql.NullString
	Src    sql.NullString
}

type ImageLicense struct {
	ImageID   sql.NullInt64
	LicenseID sql.NullInt64
}

type IntlStatus struct {
	ID   int64
	Name sql.NullString
	Link sql.NullString
}

type License struct {
	ID   int64
	Type sql.NullString
	Name sql.NullString
	Link sql.NullString
}

type NationalPark struct {
	ID                  int64
	Name                interface{}
	Link                sql.NullString
	Year                sql.NullInt64
	TotalAreaInKm       sql.NullInt64
	TotalAreaInMiles    sql.NullInt64
	WaterPercentages    sql.NullString
	Region              sql.NullString
	Description         sql.NullString
	CoordinateLatitude  sql.NullFloat64
	CoordinateLongitude sql.NullFloat64
	MapUrl              sql.NullString
	Location            sql.NullString
	Established         sql.NullInt64
	Visitors            sql.NullString
	Management          sql.NullString
}

type NationalParkImage struct {
	NationalParkID sql.NullInt64
	ImageID        sql.NullInt64
}

type NationalParkIntlStatus struct {
	NationalParkID sql.NullInt64
	IntlStatusID   sql.NullInt64
}
