// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Image struct {
	ID     int64
	Link   string
	Title  string
	Date   *string
	Source *string
	Author *string
	Src    *string
}

type ImageLicense struct {
	ImageID   int64
	LicenseID int64
}

type IntlStatus struct {
	ID   int64
	Name string
	Link *string
}

type License struct {
	ID   int64
	Type string
	Name string
	Link *string
}

type NationalPark struct {
	ID                  int64
	Name                string
	Link                *string
	TotalAreaInKm       *int64
	TotalAreaInMiles    *int64
	WaterPercentages    *string
	Region              string
	Description         string
	CoordinateLatitude  float64
	CoordinateLongitude float64
	MapUrl              *string
	Location            string
	EstablishedYear     int64
	Visitors            *string
	Management          *string
}

type NationalParkImage struct {
	NationalParkID int64
	ImageID        int64
}

type NationalParkIntlStatus struct {
	NationalParkID int64
	IntlStatusID   int64
}
